//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKULOTOMASYON
{
    using System;
    using System.Collections.Generic;
    
    public partial class AYARLAR
    {
        public int AYARLARID { get; set; }
        public string OGRTSİFRE { get; set; }
    
        public virtual OGRETMENLER OGRETMENLER { get; set; }
    }
}
