//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKULOTOMASYON
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRAYARLAR
    {
        public int AYARLAROGRID { get; set; }
        public string OGRSİFRE { get; set; }
    
        public virtual OGRENCİLER OGRENCİLER { get; set; }
    }
}
