//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKULOTOMASYON
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRETMENLER
    {
        public int OGTRID { get; set; }
        public string OGRTAD { get; set; }
        public string OGRTSOYAD { get; set; }
        public string OGRTTC { get; set; }
        public string OGRTTEL { get; set; }
        public string OGRTMAİL { get; set; }
        public string OGRTİL { get; set; }
        public string OGRTİLCE { get; set; }
        public string OGRTADRES { get; set; }
        public string OGRTBRANS { get; set; }
        public string OGRTFOTO { get; set; }
    
        public virtual AYARLAR AYARLAR { get; set; }
    }
}
