//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKULOTOMASYON
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbOkulEntities : DbContext
    {
        public DbOkulEntities()
            : base("name=DbOkulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Iller> Iller { get; set; }
        public virtual DbSet<OGRENCİLER> OGRENCİLER { get; set; }
        public virtual DbSet<OGRETMENLER> OGRETMENLER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_BRANSLAR> TBL_BRANSLAR { get; set; }
        public virtual DbSet<VELİLER> VELİLER { get; set; }
        public virtual DbSet<AYARLAR> AYARLARs { get; set; }
        public virtual DbSet<OGRAYARLAR> OGRAYARLARs { get; set; }
    
        public virtual ObjectResult<AyarlarOgrenciler_Result> AyarlarOgrenciler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AyarlarOgrenciler_Result>("AyarlarOgrenciler");
        }
    }
}
